### ISSUE TITLE
Activation server documentation

### ISSUE THREAD

**Issue by Lewiscowles1986** [audible-tools/audible-tools.github.io#1]
Is there documentation available on the sources of the servers for:

https://github.com/audible-tools/audible-tools.github.io/commit/d3f6a58f9b84ef21e58a827c5c8c812f16c594c3

I Can't find anything in the code. Is it official Amazon?

**Comment by JKamsker** [comment]
Thanks for your interest in my little side-project

No its my private server.
The source is only partially public available. (The client)
Feel free to use the api for personal projects. I'd be happy to hear what you make out of it :)

**Comment by JKamsker** [comment]
... little follow-up: As stated in the source, you basically make a GET request to the server and it returns a json object

for e.g.
```json
{
  "success": true,
  "activationBytes": "abcdef19"
}
```

If you wish, you can also check the result the same way, the client does it (https://github.com/audible-tools/audible-tools.github.io/blob/master/src/ChecksumResolver.js#L150)

**Comment by Lewiscowles1986** [comment]
Thanks so much 🙇 .

I'm literally only using it for personal liberty so that I can listen to audio-books without the few MB it seems to add to file-sizes, and without internet access. 

The alternative seemed to be a tool that was trying to monetize removing the protections meaning I'd pay Audible and some intermediary, or fixing up a python script (probably easier than it sounds), or if I'm honest, loopbacking audio and playing aax via audible in a VM or container (works for my use-case as I do use a valid audible account to ensure creators are paid something).

**Comment by JKamsker** [comment]
Cool! I'm happy that somebody actually finds the stuff i do useful :D

Have you tried the ffmpeg command [audible-tools.github.io](https://audible-tools.github.io/) generates?

There are some other options you might not have heared about:

- [openaudible](https://openaudible.org/) - Paid
- [Libation](https://github.com/rmcrackan/Libation) - Free, ugly source af and Windows only, but downloads your whole library automatically if you like 
- [AaxAudioConverter](https://github.com/audiamus/AaxAudioConverter) - Free but Windows only i guess
- [inAudible](https://github.com/rmcrackan/inAudible) - Free Win/Mac



More lecture about this topic: https://github.com/rmcrackan/AudiobookHub

**Comment by Lewiscowles1986** [comment]
I have for FLAC and m4b / AAC formats

I also found the support for drag and drop interesting, fast and intuitive.

**Comment by JKamsker** [comment]
Cool, yea i thought like "yea maybe smth like that could be useful, i'd use that"...then i spend a ungodly amount of time implementing it :D

Lmk if you have any ideas for improvement

**Comment by Lewiscowles1986** [comment]
I'm looking at the code while listening to audiobook I used it on. 😁 

What sort of feedback or input are you looking for?
Are there pain points you have working on this?

**Comment by Lewiscowles1986** [comment]
Mentioned you in a severely limited spike on cutting out all the UI from this 😂

**Comment by JKamsker** [comment]
> I'm looking at the code while listening to audiobook I used it on. 😁

Lol 

> What sort of feedback or input are you looking for?
> Are there pain points you have working on this?

Something that might be useful to the app. 
The project is primarely a tiny sideproject for me to learn React and retain the knowledge every now and then :P

**Comment by Lewiscowles1986** [comment]
Ah... In that case I'll open some tickets. All I spotted were composition bug-bears, but it's also difficult to test as-is.

**Comment by JKamsker** [comment]
Wait what? You can test UI? Oo

**Comment by JKamsker** [comment]
@Lewiscowles1986 https://github.com/audible-tools/Api-Documentation
Can you have a look at it and maybe pr stuff i might have forgotten?
