### ISSUE TITLE
iAmDeaf

### ISSUE THREAD

**Issue by writetome1** [audible-tools/audible-tools.github.io#13]
iAmDeaf version still use aaxc,,  +
.voucher file: “/data/data/com.audible.application/files/vouchers/”
.database file: “/data/data/com.audible.application/databases/”     map_data_storage_v2.db
aaxc is there but,  as I can see, vouchers and db file are missed 
I'm not sure ( I'm on android no root) I'm right ? 
I just see a file .companion !  New audible version ?

**Comment by JKamsker** [comment]
Aaxc is not supported, just aax.
