### ISSUE TITLE
Missing project for the actual activation code?

### ISSUE THREAD

**Issue by jmt-gh** [audible-tools/audible-tools.github.io#19]
Hi! Looking to run this locally, but I noticed that the project/function you're hosting here `https://aaxapiserverfunction20220831180001.azurewebsites.net`, seems to not be included in this project? Can you point me to where it is, if anywhere?

**Comment by JKamsker** [comment]
That part of the project is unfortunately not opensource.

**Comment by StupidRepo** [comment]
Why not?

**Comment by JKamsker** [comment]
Its not stealing if everyone gives them to me😂 /s

No fr, look it up, no audio data is getting send anywhere. Its all in browser @StupidRepo

**Comment by StupidRepo** [comment]
> Its not stealing if everyone gives them to me😂 /s

True tbf..

> No fr, look it up, no audio data is getting send anywhere. Its all in browser 

Really? How come it's uploading stuff to the server and needs reCaptcha? 💀

**Comment by StupidRepo** [comment]
I assume it's using some kind of bruteforce, but then how come it can send it back within less than a second? @JKamsker

**Comment by JKamsker** [comment]
> I assume it's using some kind of bruteforce, but then how come it can send it back within less than a second? [@JKamsker](https://github.com/JKamsker)

![Magic](https://media1.tenor.com/m/wn2_Qq6flogAAAAC/magical-magic.gif)

**Comment by StupidRepo** [comment]
Lmao fair enough. Is it true that each set of activation bytes is linked to an account? 💀

**Comment by StupidRepo** [comment]
> > I assume it's using some kind of bruteforce, but then how come it can send it back within less than a second? [@JKamsker](https://github.com/JKamsker)
> 
> ![Magic](https://media1.tenor.com/m/wn2_Qq6flogAAAAC/magical-magic.gif)
> 

I'm so dumb! I assume you have got a list of every activation code possible, and then hash them all. Then when a hash/checksum is put into the website it just looks it up.

Very smart!
