### ISSUE TITLE
No License Specified

### ISSUE THREAD

**Issue by JacobCarrell** [audible-tools/audible-tools.github.io#20]
Please define a license in the repo properties, and if that doesn't create it- add a license.md as well please. I'd love to include this as part of a larger project, but cannot until a license is specified.

Thanks for an awesome tool!

**Comment by JKamsker** [comment]
Added a license that is based on the MIT license. Hope that is sufficient for your usecase.

May i ask which project you are working on?

**Comment by JacobCarrell** [comment]
Perfect, I just needed *any* license- without one specified it defaults to all rights reserved under US Copyright Law.

And, it's a stretch goal- but I want to combine a bunch of tools to work with audiobooks-
* Decrypt AAX(C) sans transcode, with chapters- and maybe somehow get whispersync working.
* General transcode- looks like Opus can handle chapter metadata.
* Detect and remove false stereo channels (its mono, but they added a stereo channel)
* Noise reduction
* detect excessive bit depth and sampling
* Merge and chapterize multiple files, any format, (mp3 will have a CUE file and/or some metadata.

If I can get it running, restoration options for tape, end of track 'please insert next part' removal.
