### ISSUE TITLE
In Browser conversion stopped working

### ISSUE THREAD

**Issue by csandman** [audible-tools/audible-tools.github.io#4]
This was working fine for me a few days ago but it looks like it is no longer working because chrome changed the rules for using `SharedArrayBuffer`.  This is the error I'm getting:

```
[Deprecation] SharedArrayBuffer will require cross-origin isolation as of M92, around July 2021. See https://developer.chrome.com/blog/enabling-shared-array-buffer/ for more details.
Uncaught (in promise) ReferenceError: SharedArrayBuffer is not defined
    at 055b4913-ac8e-4b88-82cf-3c0aec6c7543:22
    at createFFmpeg.js:64
    at s (runtime.js:63)
    at Generator._invoke (runtime.js:293)
    at Generator.next (runtime.js:118)
    at n (asyncToGenerator.js:3)
    at l (asyncToGenerator.js:25)
```

Here is the article it links to: https://developer.chrome.com/blog/enabling-shared-array-buffer/#cross-origin-isolation

Apparently you need to serve the main document with the following headers:

```
Cross-Origin-Embedder-Policy: require-corp
Cross-Origin-Opener-Policy: same-origin
```

I'm not sure if this is possible when using GitHub pages but I thought I'd let you know!

**Comment by csandman** [comment]
It looks like there's already an issue about this on the ffmpeg.wasm repo: https://github.com/ffmpegwasm/ffmpeg.wasm/issues/231

**Comment by JKamsker** [comment]
Ah yea. Fixed this a while ago but was too lazy deploying a redirect xD

The new url is https://audible-converter.ml
This should fix the issue

**Comment by JKamsker** [comment]
Just found out that i can change the settings that gp pages 301 to the new site :3

**Comment by csandman** [comment]
Thanks for the quick turnaround on this!
